### ISSUE TITLE
Issues on useMercadopago cleanup

### ISSUE THREAD

**Issue by eduardotomassiwakapi** [s4mukka/react-sdk-mercadopago#2]
Hi,
- I'm having an issue when a component using useMercadopago gets unmounted on a test site

**v2.ts:32** Uncaught DOMException: Failed to execute '**removeChild**' on 'Node': The node to be removed is not a child of this node.
    at http://localhost:3000/static/js/vendors~main.chunk.js:146474:23
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/vendors~main.chunk.js:111949:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/vendors~main.chunk.js:111998:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/vendors~main.chunk.js:112051:35)
    at safelyCallDestroy (http://localhost:3000/static/js/vendors~main.chunk.js:131257:9)
    at http://localhost:3000/static/js/vendors~main.chunk.js:131719:25
    at unstable_runWithPriority (http://localhost:3000/static/js/vendors~main.chunk.js:152469:16)
    at runWithPriority$1 (http://localhost:3000/static/js/vendors~main.chunk.js:122836:14)
    at commitUnmount (http://localhost:3000/static/js/vendors~main.chunk.js:131712:19)
    at unmountHostComponents (http://localhost:3000/static/js/vendors~main.chunk.js:132082:11)
    at commitDeletion (http://localhost:3000/static/js/vendors~main.chunk.js:132118:9)
    at commitMutationEffects (http://localhost:3000/static/js/vendors~main.chunk.js:134398:15)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/vendors~main.chunk.js:111949:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/vendors~main.chunk.js:111998:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/vendors~main.chunk.js:112051:35)
    at commitRootImpl (http://localhost:3000/static/js/vendors~main.chunk.js:134129:13)
    at unstable_runWithPriority (http://localhost:3000/static/js/vendors~main.chunk.js:152469:16)
    at runWithPriority$1 (http://localhost:3000/static/js/vendors~main.chunk.js:122836:14)
    at commitRoot (http://localhost:3000/static/js/vendors~main.chunk.js:134003:7)
    at finishSyncRender (http://localhost:3000/static/js/vendors~main.chunk.js:133420:7)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/vendors~main.chunk.js:133406:11)
    at http://localhost:3000/static/js/vendors~main.chunk.js:122890:28
    at unstable_runWithPriority (http://localhost:3000/static/js/vendors~main.chunk.js:152469:16)
    at runWithPriority$1 (http://localhost:3000/static/js/vendors~main.chunk.js:122836:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/vendors~main.chunk.js:122885:11)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/vendors~main.chunk.js:122873:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/vendors~main.chunk.js:134495:7)
    at unstable_runWithPriority (http://localhost:3000/static/js/vendors~main.chunk.js:152469:16)
    at runWithPriority$1 (http://localhost:3000/static/js/vendors~main.chunk.js:122836:14)
    at flushPassiveEffects (http://localhost:3000/static/js/vendors~main.chunk.js:134436:16)
    at http://localhost:3000/static/js/vendors~main.chunk.js:134315:15
    at workLoop (http://localhost:3000/static/js/vendors~main.chunk.js:152413:38)
    at flushWork (http://localhost:3000/static/js/vendors~main.chunk.js:152369:20)
    at MessagePort.performWorkUntilDeadline (http://localhost:3000/static/js/vendors~main.chunk.js:151973:31)

- I am also experiencing several CORS issues on the console:

Access to XMLHttpRequest at 'https://events.mercadopago.com/v2/traffic-light' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field x-request-id is not allowed by Access-Control-Allow-Headers in preflight response.
POST https://events.mercadopago.com/v2/traffic-light net::ERR_FAILED

It is working on the sale perspective, at least with test credentials, but my site is now crashing on the component unmount because it can not find the DOM node to remove the script on [THIS FILE](https://github.com/s4mukka/react-sdk-mercadopago/blob/master/src/v2.ts) line 32

Thank you in advance, I am willing to help if needed.

**Comment by eduardotomassiwakapi** [comment]
this was an internal mercadopago js sdk issue
https://github.com/mercadopago/sdk-js/issues/25

I'm closing it

**Comment by eduardotomassiwakapi** [comment]
Hi again,
Unfortunately I am still having issues with the removeChild
The CORS thing was solved in the mercadopago js sdk but I am still getting this:
![image](https://user-images.githubusercontent.com/66016615/124182428-389d2a00-da8d-11eb-9d29-c1b52092c208.png)
![image](https://user-images.githubusercontent.com/66016615/124182513-54a0cb80-da8d-11eb-85c1-396fed7a6fc3.png)
Not sure why because this was working last week.

**Comment by s4mukka** [comment]
When does this error occur?

**Comment by eduardotomassiwakapi** [comment]
Hi @s4mukka 
It's happening on the unmount of the component that is using useMercadopago.
I am dispatching a new sale to my back, and upon success I'm doing a history.replace('/success') and now this is failing on that removeChild which is weird because it was working before.
Any idea?

**Comment by s4mukka** [comment]
When the component is assembled, in which part of the html is the iframe generated by mercadopago?
It is expected that it will be generated as a child of the body.
![image](https://user-images.githubusercontent.com/50877271/124500781-bf584c80-dd96-11eb-9339-32bfeb766a4e.png)

**Comment by s4mukka** [comment]
I made an update that might fix the problem.
It is at version 1.1.1

**Comment by eduardotomassiwakapi** [comment]
I ended up removing the component and manually handling the script. but seems like this fix might solve the issue.
Thanks man
